
[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sport-facilities-map"
version = "1.0.0"
description = "Interactive map of sport facilities"
